service: meverty-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-2
          
custom:
  wsgi:
    app: src/app.app
    packRequirements: false
  pythonRequirements:
    pythonBin: python3
    dockerizePip: false

plugins:
  - serverless-wsgi
  - serverless-python-requirements
functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY