name: dev-deploy

on:
  pull_request:
    branches: main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - run: npm install
    - uses: actions/setup-python
      with: 
        python-version: '3.8'
        cache: 'pip'

    - run: pip install -r requirements.txt

    - uses: serverless/github-action@v3
      with:
        args: deploy -s v1